// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4owGs8te_N8Hb-sfZV7XthVWJNcoE-AI',
    appId: '1:167852024232:web:865aa44ab8d5428f7efd9d',
    messagingSenderId: '167852024232',
    projectId: 'albamate-capstone-01',
    authDomain: 'albamate-capstone-01.firebaseapp.com',
    databaseURL: 'https://albamate-capstone-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albamate-capstone-01.firebasestorage.app',
    measurementId: 'G-79GNHMH1E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuXiZf4-2-klcKa336-QAadcvM5nl-_rY',
    appId: '1:167852024232:android:e6c7faa9fd9d254f7efd9d',
    messagingSenderId: '167852024232',
    projectId: 'albamate-capstone-01',
    databaseURL: 'https://albamate-capstone-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albamate-capstone-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCorV_7J4rkyYHC7yDiQnWkNAcj35hQtI',
    appId: '1:167852024232:ios:93278183efb8a0107efd9d',
    messagingSenderId: '167852024232',
    projectId: 'albamate-capstone-01',
    databaseURL: 'https://albamate-capstone-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albamate-capstone-01.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCorV_7J4rkyYHC7yDiQnWkNAcj35hQtI',
    appId: '1:167852024232:ios:93278183efb8a0107efd9d',
    messagingSenderId: '167852024232',
    projectId: 'albamate-capstone-01',
    databaseURL: 'https://albamate-capstone-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albamate-capstone-01.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4owGs8te_N8Hb-sfZV7XthVWJNcoE-AI',
    appId: '1:167852024232:web:1ef2ad819c3ae38f7efd9d',
    messagingSenderId: '167852024232',
    projectId: 'albamate-capstone-01',
    authDomain: 'albamate-capstone-01.firebaseapp.com',
    databaseURL: 'https://albamate-capstone-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albamate-capstone-01.firebasestorage.app',
    measurementId: 'G-KHX0HMLBHR',
  );
}
